In [105]:
import os

base_path = !pwd
base_path = base_path[0]
list_files = [base_path+"/data/caligraph/"+f for f in os.listdir(base_path+"/data/caligraph/") if os.path.isfile(base_path+"/data/caligraph/"+f)]

In [106]:
list_files

['/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-provenance.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-transitive-types.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-to-dbpedia-mappings.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-labels.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-ontology.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-relations.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-types.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-class-to-dbpedia.nt',
 '/home/nkouagou/Documents/Universal_Embeddings/data/caligraph/caligraph-instance-provenance.nt']

In [107]:
with open(list_files[2]) as file:
    instance_to_dbpedia_mappings = file.readlines()

In [112]:
def get_map(mapping):
    x,_,y,_ = mapping.split()
    return x,y

In [113]:
instance_to_dbpedia_mappings = dict(map(lambda x: get_map(x), instance_to_dbpedia_mappings))

In [136]:
list(instance_to_dbpedia_mappings.items())[13]

('<http://caligraph.org/resource/Cameroon_sheep>',
 '<http://dbpedia.org/resource/Cameroon_sheep>')

In [116]:
len(instance_to_dbpedia_mappings)

8320865

### Aligning entity embeddings using procruste approach

In [101]:
import numpy as np

In [102]:
from gensim.test.utils import get_tmpfile
from gensim.models import KeyedVectors

In [103]:
word_vectors_caligraph = KeyedVectors.load("./embeddings/caligraph/caligraph.kv", mmap='r')

In [104]:
word_vectors_dbpedia = KeyedVectors.load("./embeddings/dbpedia/dbpedia.kv", mmap='r')

In [159]:
mappings_of_interest = dict()
for ent_cal, ent_db in instance_to_dbpedia_mappings.items():
    if 'dbr:'+ent_db.strip('<http://dbpedia.org/resource/>') in word_vectors_dbpedia.key_to_index:
        mappings_of_interest[ent_cal] = 'dbr:'+ent_db.strip('<http://dbpedia.org/resource/>')

In [160]:
len(mappings_of_interest)

1707613

In [130]:
len(instance_to_dbpedia_mappings)

8320865

In [39]:
ent1_cal, ent1_db = 'http://caligraph.org/resource/Yatel_F.C.__Ricky_Tari__1', 'http://dbpedia.org/resource/Yatel_F.C.__Ricky_Tari__1'

In [47]:
#ent1_emb_cal, ent1_emb_db = word_vectors_caligraph.get_vector(ent1_cal), word_vectors_dbpedia.get_vector(ent1_db)

In [44]:
'dbpedia.org/resource/Yatel_F.C.__Ricky_Tari__1' in word_vectors_dbpedia.key_to_index

False

In [167]:
no_dbr = []
for ent in word_vectors_dbpedia.key_to_index.keys():
    if not 'dbr:' in ent and '#' in ent:
        no_dbr.append(ent)

In [176]:
list(word_vectors_caligraph.key_to_index.keys())[:20]

['http://caligraph.org/resource/Marcus_Ginyard__3',
 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type',
 'http://www.w3.org/2002/07/owl#NamedIndividual',
 'http://caligraph.org/ontology/Time_period',
 'http://www.w3.org/2002/07/owl#Class',
 'http://www.w3.org/2000/01/rdf-schema#subClassOf',
 'http://www.w3.org/2002/07/owl#Thing',
 'http://caligraph.org/resource/Synagogues:_Transformation_and_Renewal',
 'http://caligraph.org/ontology/Jewish_organization_based_in_the_United_States',
 'http://caligraph.org/ontology/Organisation',
 'http://caligraph.org/ontology/Religious_organization_based_in_the_United_States',
 'http://caligraph.org/ontology/Agent',
 'http://caligraph.org/ontology/Organization_based_in_the_United_States',
 'http://caligraph.org/ontology/Organization_based_in_the_Americas',
 'http://caligraph.org/ontology/Organization_based_in_North_America',
 'http://caligraph.org/ontology/Religious_organization_in_North_America',
 'http://caligraph.org/ontology/Religious_organization',

In [178]:
i=0
for ent in instance_to_dbpedia_mappings:
    if not ent in word_vectors_caligraph.key_to_index:
        print(ent)
        i += 1
        if i > 20: break

<http://caligraph.org/resource/Yatel_F.C.__Ricky_Tari__1>
<http://caligraph.org/resource/Nepytia_janetae>
<http://caligraph.org/resource/Penbontrhydyfoethau>
<http://caligraph.org/resource/Gurgy-le-Ch%C3%A2teau>
<http://caligraph.org/resource/V%C3%A1gner_Kaetano_Pereira__CareerStation__3>
<http://caligraph.org/resource/Ferri%C3%A8res-sur-Sichon>
<http://caligraph.org/resource/Allie_Clifton>
<http://caligraph.org/resource/Jacobus_Zegers>
<http://caligraph.org/resource/Togainu_no_Chi>
<http://caligraph.org/resource/Zumpahuac%C3%A1n>
<http://caligraph.org/resource/Joubert_syndrome>
<http://caligraph.org/resource/Beverley_Baxter>
<http://caligraph.org/resource/Jonathan_David_G%C3%B3mez__CareerStation__2>
<http://caligraph.org/resource/Cameroon_sheep>
<http://caligraph.org/resource/Neil_Adams_(judoka)>
<http://caligraph.org/resource/Lyginopteridales>
<http://caligraph.org/resource/Ufia_language>
<http://caligraph.org/resource/Cassius_Winston>
<http://caligraph.org/resource/Habo_Wolley>
<htt

## Aligning dbpedia embeddings from different embedding models

In [2]:
#!pip3 install scipy

In [1]:
from scipy.spatial import procrustes
import json
from tqdm import tqdm
#a = np.array([[1, 3], [1, 2], [-1, 1], [2, 1]])
#b = np.array([[4, -2], [4, -4], [4, -6], [2, -6]])
#mtx1, mtx2, disparity = procrustes(a, b)
#disparity

In [2]:
import importlib  
kg_embedding_service = importlib.import_module("kg-embedding-service")

In [3]:
service = kg_embedding_service.KgEmbeddingService()

In [4]:
# Get all entity names
# entities = service.get_all_entity(indexname='shallom_dbpedia_index', size=0, timeout=1500)

In [5]:
#transe_dbpedia_dot_entity
#entities_transE = service.get_all_entity(indexname='transe_dbpedia_l2_entity', size=0, timeout=1500)

In [6]:
with open('dbpedia_entities.txt') as file:
    entities = file.read().split(',')

In [7]:
#entities = entities['entitylist']
len(entities)

6380141

In [6]:
#with open("dbpedia_entities.txt", "w") as file:
#    file.write(','.join(entities['entitylist']))

In [16]:
import random

In [25]:
#"indexname":"shallom_dbpedia_index","entity" : "/resource/Paderborn"
service.get_entity_embedding(indexname='shallom_dbpedia_index', entities=random.choice(entities))

{'/resource/AfterMASH__Staph_Inspection': [0.07842497,
  -0.0020045615,
  0.032735057,
  -0.07590501,
  -0.05485081,
  0.075956345,
  0.04250958,
  0.01331504,
  -0.08456255,
  0.038471743,
  -0.032615673,
  0.020639336,
  0.05653411,
  -0.1089035,
  0.0727762,
  -0.09921414,
  0.045873176,
  -0.01994859,
  -0.113333456,
  0.05731021,
  -0.027710872,
  -0.028991358,
  0.111020796,
  -0.046478495,
  0.049853314]}

In [9]:
#dbpedia_embs = service.get_entity_embedding(indexname='shallom_dbpedia_index', entities=entities['entitylist'], timeout=2500)

In [21]:
#dbpedia_embs_transe = service.get_entity_embedding(indexname='transe_dbpedia_l2_entity', entities=entities['entitylist'], timeout=2500)

In [14]:
#dbpedia_embs = {}
#for entity in tqdm(entities, desc='Iterating through entities'):
#    dbpedia_embs.update(service.get_entity_embedding(indexname='shallom_dbpedia_index', entities=entity))

#dbpedia_embs = service.get_entity_embedding(indexname='shallom_dbpedia_index', entities=entities, timeout=500)

In [15]:
#dbpedia_embs_transe = {}
#for entity in tqdm(entities, desc='Iterating through entities'):
#    dbpedia_embs_TransE.update(service.get_entity_embedding(indexname='transe_dbpedia_l2_entity', entities=entity))

#dbpedia_embs_transe = service.get_entity_embedding(indexname='transe_dbpedia_l2_entity', entities=entities, timeout=500)

### WN18RR Hypercomplex Embeddings Alignement (ConvOBatch and OMult)

In [54]:
from scipy.spatial import procrustes
import torch
import time

In [28]:
OMult = torch.load('./PretrainedModels/WN18RR/OMult/model.pt', map_location='cpu')

In [37]:
ConvOB = torch.load('./PretrainedModels/WN18RR/ConvOBatch/model.pt', map_location='cpu')

In [42]:
ConvOB['emb_ent_e0.weight'] == OMult['emb_ent_e0.weight']

tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]])

In [43]:
OMult['emb_ent_e0.weight'].shape == ConvOB['emb_ent_e0.weight'].shape

True

In [53]:
OMult['emb_ent_e0.weight'].shape

torch.Size([40943, 50])

In [44]:
OMult_comp_0, ConvOB_comp_0 = OMult['emb_ent_e0.weight'], ConvOB['emb_ent_e0.weight']

In [55]:
t0 = time.time()
mtx1, mtx2, disparity = procrustes(OMult_comp_0, ConvOB_comp_0)
print('Duration: '+str(time.time()-t0)+' seconds')

Duration: 1.75942063331604 seconds


In [56]:
disparity

0.9868089117703642

In [51]:
OMult_comp_0

tensor([[ 0.0376,  0.4348,  0.0523,  ..., -0.2622, -0.5699, -0.0317],
        [-0.5555,  0.2017,  0.2606,  ..., -0.1425, -0.2614, -0.0739],
        [ 0.0089,  0.3296, -0.2083,  ..., -0.3334, -0.4343, -0.0184],
        ...,
        [ 0.0651, -0.1014,  0.4165,  ...,  0.0905,  0.0458, -0.1385],
        [-0.3535, -0.0482, -0.1047,  ..., -0.4963, -0.2775,  0.3353],
        [-0.0208,  0.2267,  0.2854,  ..., -0.1651, -0.0494,  0.4157]])

In [52]:
ConvOB_comp_0

tensor([[-0.0933,  0.0830,  0.0292,  ..., -0.0491, -0.2728,  0.2972],
        [-0.0977, -0.0731, -0.0705,  ...,  0.0092,  0.0058, -0.0992],
        [ 0.1643, -0.2245, -0.0308,  ..., -0.0642, -0.1378,  0.1731],
        ...,
        [ 0.0034, -0.0556,  0.0544,  ..., -0.0479, -0.0574,  0.0070],
        [-0.0035, -0.0722,  0.0918,  ..., -0.0526, -0.0703,  0.2389],
        [ 0.1858, -0.0287,  0.0790,  ..., -0.0626,  0.0091,  0.1763]])

In [49]:
mtx1

array([[ 6.35564100e-04,  8.88781444e-04, -2.63558643e-05, ...,
        -4.46320908e-04, -1.52981538e-03, -9.18462068e-04],
       [-1.82539730e-03, -7.83796267e-05,  8.37960855e-04, ...,
         5.00512475e-05, -2.49916536e-04, -1.09389072e-03],
       [ 5.16577121e-04,  4.52292766e-04, -1.10771310e-03, ...,
        -7.41854893e-04, -9.67326511e-04, -8.63548931e-04],
       ...,
       [ 7.49853386e-04, -1.33589613e-03,  1.48487704e-03, ...,
         1.01694736e-03,  1.02471221e-03, -1.36159353e-03],
       [-9.87071021e-04, -1.11530446e-03, -6.77703475e-04, ...,
        -1.41793029e-03, -3.16577441e-04,  6.04256823e-04],
       [ 3.93568038e-04,  2.53464289e-05,  9.40934406e-04, ...,
        -4.36083118e-05,  6.29905473e-04,  9.37880156e-04]])

In [50]:
mtx2

array([[ 9.96808846e-05,  3.71333258e-05,  2.29807767e-05, ...,
        -1.91522404e-04, -1.26440021e-04, -1.02825719e-04],
       [-1.09107986e-04, -1.05565239e-04, -9.72885466e-05, ...,
        -1.63521861e-04, -1.33545010e-04, -4.96011984e-05],
       [ 8.82163334e-05, -3.24449166e-05,  9.78392738e-05, ...,
        -2.32842101e-04, -2.17748463e-04,  2.61813162e-05],
       ...,
       [-1.08990834e-04, -1.44352266e-04,  5.90520757e-05, ...,
        -1.20518432e-04, -1.77152774e-05, -3.18705043e-05],
       [ 4.68939021e-05, -4.02082179e-05, -2.82953422e-05, ...,
        -8.57312063e-05, -8.84345730e-05,  3.54342994e-05],
       [-8.76955526e-05, -4.21410179e-06, -1.02009482e-04, ...,
        -1.54733950e-05,  1.04668835e-04,  4.59388240e-05]])

In [57]:
mtx2.shape

(40943, 50)